apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: solver-director-skaffold
build:
  artifacts:
    - image: solver-director-skaffold
      context: .
  tagPolicy:
    gitCommit: {}


profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: solver-controller-skaffold
          context: ../solver-controller
      - op: add
        path: /build/artifacts/-
        value:
          image: data-gatherer-skaffold
          context: ../data-gatherer
    build:
      local:
        push: false
    deploy:
      helm:
        releases:
          - name: solver-director-database
            chartPath: helm/database
            namespace: psp
            wait: true
          - name: solver-director
            chartPath: helm/app
            namespace: psp
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED_solver_director_skaffold}}"
              solverController.image: "{{.IMAGE_FULLY_QUALIFIED_solver_controller_skaffold}}"
              dataGatherer.image: "{{.IMAGE_FULLY_QUALIFIED_data_gatherer_skaffold}}"
            valuesFiles:
              - helm/app/values-dev.yaml


  - name: prod
    deploy:
      helm:
        releases:
          - name: solver-director-database
            chartPath: helm/database
            namespace: psp
            wait: true
          - name: solver-director
            chartPath: helm/app
            namespace: psp
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            wait: true
            upgradeOnChange: true

