apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: solver-director-skaffold
build:
  artifacts:
    - image: solver-director-skaffold
      context: .
  tagPolicy:
    gitCommit: {}


profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
    deploy:
      helm:
        releases:
          - name: solver-director
            chartPath: helm
            namespace: default
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            setValues:
              db.host: postgresql.primvary.svc.cluster.local
              db.port: "5432"
              db.name: appdb
              db.user: appuser
              db.passwordSecretName: app-db-credetials


          - name: metrics-server
            repo: https://kubernetes-sigs.github.io/metrics-server/
            remoteChart: metrics-server
            namespace: kube-system
            setValues:
              args[0]: --kubelet-insecure-tls

          - name: postgres
            remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
            version: 16.7.27
            namespace: kube-system
            setValues:
              global.postgresql.auth.username: appuser
              global.postgresql.auth.password: devpass
              global.postgresql.auth.database: appdb
              primary.persistence.enabled: false
          

  - name: staging
    build:
      local:
        push: false # TODO set to true
      # optional: set your staging registry
      # defaultRepo: "registry.example.com/staging"
    deploy:
      helm:
        releases:
          - name: solver-director
            chartPath: helm
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            valuesFiles:
              - helm/values-prod.yaml
            wait: true
            upgradeOnChange: true

          - name: metrics-server
            repo: https://kubernetes-sigs.github.io/metrics-server/
            remoteChart: metrics-server
            namespace: kube-system
            setValues:
              args[0]: --kubelet-insecure-tls

  - name: prod
    build:
      local:
        push: true
      # optional: set your prod registry
      # defaultRepo: "registry.example.com/prod"
    deploy:
      helm:
        releases:
          - name: solver-director
            chartPath: helm
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            valuesFiles:
              - helm/values-prod.yaml
            wait: true
            upgradeOnChange: true

          - name: metrics-server
            repo: https://kubernetes-sigs.github.io/metrics-server/
            remoteChart: metrics-server
            namespace: kube-system