apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: solver-director-skaffold
build:
  artifacts:
    - image: solver-director-skaffold
      context: .
  tagPolicy:
    gitCommit: {}


profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
    deploy:
      helm:
        releases:
          - name: solver-director
            chartPath: helm
            namespace: psp
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"

          

  - name: staging
    build:
      local:
        push: false # TODO set to true
      # optional: set your staging registry
      # defaultRepo: "registry.example.com/staging"
    deploy:
      helm:
        releases:
          - name: solver-director
            chartPath: helm
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            valuesFiles:
              - helm/values-prod.yaml
            wait: true
            upgradeOnChange: true


  - name: prod
    build:
      local:
        push: true
      # optional: set your prod registry
      # defaultRepo: "registry.example.com/prod"
    deploy:
      helm:
        releases:
          - name: solver-director
            chartPath: helm
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            valuesFiles:
              - helm/values-prod.yaml
            wait: true
            upgradeOnChange: true

