"""add_resource_limits

Revision ID: 1513f5e747aa
Revises: da6e1e772ff5
Create Date: 2026-03-16 11:13:18.749245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1513f5e747aa'
down_revision: Union[str, Sequence[str], None] = 'da6e1e772ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_user_cpu_cores', sa.Float(), nullable=False),
    sa.Column('per_user_memory_gib', sa.Float(), nullable=False),
    sa.Column('global_max_cpu_cores', sa.Float(), nullable=False),
    sa.Column('global_max_memory_gib', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resource_config',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=True),
    sa.Column('memory_gib', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('projects', sa.Column('requested_cpu_cores', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('projects', sa.Column('requested_memory_gib', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('projects', sa.Column('is_queued', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_queued')
    op.drop_column('projects', 'requested_memory_gib')
    op.drop_column('projects', 'requested_cpu_cores')
    op.drop_table('user_resource_config')
    op.drop_table('resource_defaults')
    # ### end Alembic commands ###
