"""

Revision ID: 3c13f4b81484
Revises: b0039aa70bca
Create Date: 2025-11-14 11:45:50.783519

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3c13f4b81484'
down_revision: Union[str, Sequence[str], None] = 'b0039aa70bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
