"""change_solver_name_to_names_array

Revision ID: 3e931dc59b58
Revises: 31032b007022
Create Date: 2025-11-28 14:29:01.848927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e931dc59b58'
down_revision: Union[str, Sequence[str], None] = '31032b007022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('solver_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_results_project_id'), 'project_results', ['project_id'], unique=False)

    # Add new names column as nullable first
    op.add_column('solvers', sa.Column('names', sa.ARRAY(sa.String()), nullable=True))

    # Migrate existing data: convert name to array with single element
    op.execute("UPDATE solvers SET names = ARRAY[name] WHERE name IS NOT NULL")

    # Now make it non-nullable
    op.alter_column('solvers', 'names', nullable=False)

    # Drop old name column
    op.drop_column('solvers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add old name column as nullable first
    op.add_column('solvers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # Migrate data back: take first element of names array
    op.execute("UPDATE solvers SET name = names[1] WHERE names IS NOT NULL AND array_length(names, 1) > 0")

    # Make it non-nullable
    op.alter_column('solvers', 'name', nullable=False)

    # Drop names column
    op.drop_column('solvers', 'names')

    op.drop_index(op.f('ix_project_results_project_id'), table_name='project_results')
    op.drop_table('project_results')
    # ### end Alembic commands ###
