"""

Revision ID: 5325ffcb2960
Revises: a05851794b57
Create Date: 2025-10-22 13:43:24.130448

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5325ffcb2960'
down_revision: Union[str, Sequence[str], None] = 'a05851794b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'problems', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='unique')
    # ### end Alembic commands ###
