"""

Revision ID: a535e52886b1
Revises: 3e931dc59b58
Create Date: 2025-12-01 09:18:07.843868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a535e52886b1'
down_revision: Union[str, Sequence[str], None] = '3e931dc59b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solver_images', sa.Column('image_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'solver_images', ['image_name'])
    op.add_column('solvers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('solvers', sa.Column('solver_image_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('solvers_solver_images_id_fkey'), 'solvers', type_='foreignkey')
    op.create_foreign_key(None, 'solvers', 'solver_images', ['solver_image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('solvers', 'solver_images_id')
    op.drop_column('solvers', 'names')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solvers', sa.Column('names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('solvers', sa.Column('solver_images_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'solvers', type_='foreignkey')
    op.create_foreign_key(op.f('solvers_solver_images_id_fkey'), 'solvers', 'solver_images', ['solver_images_id'], ['id'], ondelete='CASCADE')
    op.drop_column('solvers', 'solver_image_id')
    op.drop_column('solvers', 'name')
    op.drop_constraint(None, 'solver_images', type_='unique')
    op.drop_column('solver_images', 'image_name')
    # ### end Alembic commands ###
