"""add_is_complete_to_projects

Revision ID: da6e1e772ff5
Revises: f1fb59f4d61e
Create Date: 2026-03-12 14:28:47.674347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6e1e772ff5'
down_revision: Union[str, Sequence[str], None] = 'f1fb59f4d61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_complete')
    # ### end Alembic commands ###
