apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: solver-director-database-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: solver-director-db-kv
    kind: SecretStore
  target:
    name: solver-director-database-credentials
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: "solver-director/database-credentials"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "solver-director/database-credentials"
        property: "password"
