apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: solver-director-db-kv
spec:
  provider:
    vault:
      server: "http://secrets-manager-openbao.secrets-manager.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "solver-director-db-role"
          serviceAccountRef:
            name: "solver-director-db"
