postgres:
  image:
    repository: postgres
    tag: "15@sha256:b0a199c49fa974cf5b18c0bafb128b8023142705b23235892821fa9ac2d2cbb8"
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerName: postgresql
  service:
    name: "solver-director-postgres"
    port: 5432
  database:
    name: "solver_director"
  securityContext:
    runAsUser: 999
    runAsNonRoot: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "10Gi"
  persistence:
    claimName: "postgres-data"
    size: "1Gi"
    storageClass: "postgres-retain"
