postgres:
  image:
    repository: postgres
    tag: "15@sha256:29342cb52157b098821961d2c14eec3c019071f56a5d559e990cf07cf541ea9b"
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerName: postgresql
  service:
    name: "solver-director-postgres"
    port: 5432
  database:
    name: "solver_director"
  securityContext:
    runAsUser: 999
    runAsNonRoot: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "10Gi"
  persistence:
    claimName: "postgres-data"
    size: "1Gi"
    storageClass: "postgres-retain"
